# Generated by Django 3.2.16 on 2023-02-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('did_you_know', 'Did you know'), ('tips_and_how_tos', 'Tips and how tos'), ('fun_posts', 'Fun posts'), ('recommendations', 'Recommendations'), ('other', 'Other')], default='none', max_length=50),
        ),
    ]
