# Generated by Django 3.2.16 on 2023-01-31 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('did_you_know', 'Did_you_know'), ('tips&how_tos', 'Tips&how_tos'), ('fun_posts', 'Fun_posts'), ('recommendations', 'Recommendations'), ('other', 'Other')], default='none', max_length=50),
        ),
    ]
