# Generated by Django 3.2.16 on 2023-03-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='link',
            field=models.URLField(max_length=400, verbose_name='Workshop URL'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='time',
            field=models.TimeField(),
        ),
    ]
